# Generated by Django 4.1.7 on 2023-03-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0003_alter_canbus_changed_at_alter_car_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canbus',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAN_tool_app.car'),
        ),
        migrations.AlterField(
            model_name='message',
            name='can_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAN_tool_app.canbus'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAN_tool_app.message'),
        ),
    ]
