# Generated by Django 4.1.7 on 2023-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0004_alter_canbus_car_alter_message_can_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
