# Generated by Django 4.1.7 on 2023-03-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0005_alter_signal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_id',
            new_name='identifier',
        ),
    ]
