# Generated by Django 4.1.7 on 2023-03-16 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CAN_tool_app', '0007_rename_unit_tx_message_receivers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canbus',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='canbus',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.BooleanField(default=0)),
                ('car_year', models.BooleanField(default=0)),
                ('car_note', models.BooleanField(default=0)),
                ('car_author', models.BooleanField(default=0)),
                ('car_created_at', models.BooleanField(default=0)),
                ('car_changed_at', models.BooleanField(default=0)),
                ('can_bus_name', models.BooleanField(default=0)),
                ('can_bus_note', models.BooleanField(default=0)),
                ('can_bus_author', models.BooleanField(default=0)),
                ('can_bus_created_at', models.BooleanField(default=0)),
                ('can_bus_changed_at', models.BooleanField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
