# Generated by Django 4.1.7 on 2023-03-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0010_alter_userpreferences_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='id',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
