# Generated by Django 4.1.7 on 2023-03-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0013_alter_userpreferences_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='identifier',
            field=models.PositiveIntegerField(),
        ),
    ]
