# Generated by Django 4.1.7 on 2023-03-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0014_alter_message_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_extended_frame',
        ),
        migrations.AlterField(
            model_name='message',
            name='length',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='length',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='multiplexer_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
