# Generated by Django 4.1.7 on 2023-03-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0016_userpreferences_message_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='signal_author',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_changed_at',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_created_at',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_factor',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_is_little_endian',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_is_multiplexer',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_is_signed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_length',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_max',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_min',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_multiplexer_signal',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_multiplexer_value',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_name',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_note',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_offset',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_receivers',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_start_bit',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='signal_unit',
            field=models.BooleanField(default=0),
        ),
    ]
