# Generated by Django 4.1.7 on 2023-03-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0017_userpreferences_signal_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='signal_max',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='signal_min',
            field=models.BooleanField(default=1),
        ),
    ]
