# Generated by Django 4.1.7 on 2023-03-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0018_alter_userpreferences_signal_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='signal',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
