# Generated by Django 4.1.7 on 2023-04-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0019_alter_message_name_alter_signal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='length',
        ),
        migrations.AlterField(
            model_name='signal',
            name='factor',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='signal',
            name='offset',
            field=models.FloatField(default=0),
        ),
    ]
