# Generated by Django 4.1.7 on 2023-04-11 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0020_remove_message_length_alter_signal_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignalCheckboxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAN_tool_app.signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAN_tool_app.userpreferences')),
            ],
            options={
                'db_table': 'user_signal_checkboxes',
            },
        ),
        migrations.CreateModel(
            name='UserMessageCheckboxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAN_tool_app.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAN_tool_app.userpreferences')),
            ],
            options={
                'db_table': 'user_message_checkboxes',
            },
        ),
    ]
