# Generated by Django 4.1.7 on 2023-04-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAN_tool_app', '0021_usersignalcheckboxes_usermessagecheckboxes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessagecheckboxes',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='usersignalcheckboxes',
            old_name='signal_id',
            new_name='signal',
        ),
    ]
